### Create task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "id": 3,
  "title": "faire la vaisselle",
  "priority": "MEDIUM",
  "deadline": "2024-04-24T10:00"
}

### Get All
GET http://localhost:8080/tasks

### Get One
GET http://localhost:8080/tasks/1

### Get By Priority
GET http://localhost:8080/tasks?priority=LOW

### Delete By ID
DELETE http://localhost:8080/tasks/1

### Update
PUT http://localhost:8080/tasks
Content-Type: application/json

{
  "id": 1,
  "title": "faire la vaisselle",
  "priority": "LOW",
  "deadline": "2024-04-10T10:00"
}




### Delete past tasks - V
DELETE http://localhost:8080/tasks/past?completed=false

### Complete - V
PATCH http://localhost:8080/tasks/1/complete

### Update priority - V
PATCH http://localhost:8080/tasks/1?priority=MEDIUM

### Get Urgent - V
GET http://localhost:8080/tasks/urgent
